Import

In [300]:
import pandas as pd
import numpy as np
import seaborn as sns
from tabulate import tabulate
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [301]:
df_original = pd.read_csv(
    "./datasets/sales.csv",
    sep=None, 
    engine='python'
)

Data preparation

In [302]:
df = df_original.copy()

In [303]:
df.head()

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,Группа3,Группа4,Тип,Номенклатура,ТипТовара,Отменено,ПричинаОтмены,Количество,Цена,СуммаСтроки,ЦенаЗакупки,МесяцДатыЗаказа,ГодДатыЗаказа,ПВЗ_код,Статус,Гео,Маржа,СуммаУслуг,СуммаДоставки,НомерСтроки,КоличествоПроданоКлиенту,ДатаЗаказаНаСайте,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа
0,01.03.2017 11:41,07.03.2017 0:00,3998972_TR,Частичный возврат,12 098,12 247,Курьерская,Наличная,Москва,КРУПНОГАБАРИТНЫЙ ТОВАР,КОЛЯСКИ,АКСЕССУАРЫ ДЛЯ КОЛЯСОК,КГТ,"LEADER KIDS, МУФТА на ручку коляски, (беж),",КГТ,Нет,NaN,1,680,680,172,3,2 017,NaN,Возврат,Москва,508,0,0,8,1,28.02.2017 0:00,55574854-48574951555577,106117_ju18@yandex.ru,Юлия,ID9010020114553,0,NaN
1,01.03.2017 12:22,15.03.2017 0:00,3999117_TR,Доставлен,4 819,3 759,Магазины,Безналичная,Челябинск,"ТЕКСТИЛЬ, ТРИКОТАЖ",ОДЕЖДА ДЛЯ НОВОРОЖДЕННЫХ (0-2 лет),боди,ОДЕЖДА,"GAMEX, БОДИ кор. рук. Roza, (бел/сер), р. 86, ...",МГТ,Нет,NaN,1,379,379,"209,8",3,2 017,23111,Доставлен,Регионы,"169,2",0,0,3,1,01.03.2017 0:00,55575453-56535648535679,107117_ku16@list.ru,Гость,IDL00028974351,0,NaN
2,01.03.2017 12:31,17.03.2017 0:00,3999122_TR,Доставлен,3 325,3 325,Магазины,Безналичная,Нижневартовск,ИГРУШКИ,ИГРУШКИ ДЛЯ ДЕВОЧЕК,имитационные игрушки для девочек,ИГРУШКИ,"ИГРУША, ХОЛОДИЛЬНИК (на бат), (29,5*19*45,5 см)",МГТ,Нет,NaN,1,3 325,3 325,1 149,3,2 017,23111,Доставлен,Регионы,2 176,0,0,1,1,01.03.2017 0:00,55574950-57515657535772,109117_mu17@mail.ru,Гость,IDL00038573351,0,NaN
3,01.03.2017 3:06,02.03.2017 0:00,3999363_TR,К отгрузке,4 998,4 998,Курьерская,Наличная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ОДЕЖДА ДЛЯ НОВОРОЖДЕННЫХ (0-2 лет),ползунки,ОДЕЖДА,"MAMATTI, ПОЛЗУНКИ Elephant, р. 68, Польша",МГТ,Нет,NaN,1,330,330,"166,96",3,2 017,NaN,Доставлен,Москва,"163,04",0,0,4,0,01.03.2017 0:00,55574851-55545249535475,115117_su13@mail.ru,Гость,IDL00034303856,0,NaN
4,01.03.2017 11:38,14.03.2017 0:00,3999411_TR,Доставлен,528,528,Магазины,Безналичная,Ижевск,ИГРУШКИ,ИГРУШКИ ДЛЯ РАЗВИТИЯ МАЛЫШЕЙ,игрушки для ванной,ИГРУШКИ,"S+S TOYS, ИГРУШКА ПВХ в наборе, (2 шт)",МГТ,Нет,NaN,1,199,199,79,3,2 017,23111,Доставлен,Регионы,120,0,0,3,1,01.03.2017 0:00,55574854-56495552515179,guest_103117_gu28@workmail.ru,Гость,IDL00035791553,0,NaN

In [304]:
#вычисляем количество уникальных значений, количество нулей, количество пропусков, процент пропусков и тип данных
def columnValues(df):
    row = [df.nunique(), (df == 0).sum(axis=0), df.isna().sum(), round(df.isna().sum() / len(df) * 100, 1), df.dtypes]
    return row

data = []
for column in df:
    data.append([column] + columnValues(df[column]))

print(tabulate(data, headers=['Column', 'Count Unique', 'Count Zeros', 'Count NaNs','% of NaNs', 'data type'], tablefmt='orgtbl'))

| Column                   |   Count Unique |   Count Zeros |   Count NaNs |   % of NaNs | data type   |
|--------------------------+----------------+---------------+--------------+-------------+-------------|
| Дата                     |          28887 |             0 |            0 |         0   | object      |
| ДатаДоставки             |            107 |             0 |          626 |         0.1 | object      |
| НомерЗаказаНаСайте       |         178418 |             0 |            4 |         0   | object      |
| НовыйСтатус              |             14 |             0 |            0 |         0   | object      |
| СуммаЗаказаНаСайте       |          14316 |             0 |            0 |         0   | object      |
| СуммаДокумента           |          14747 |             0 |            0 |         0   | object      |
| МетодДоставки            |              7 |             0 |            0 |         0   | object      |
| ФормаОплаты              |              2 |             0 |            0 |         0   | object      |
| Регион                   |            508 |             0 |         5142 |         0.7 | object      |
| Группа2                  |             13 |             0 |        74686 |        10.8 | object      |
| Группа3                  |             93 |             0 |        74686 |        10.8 | object      |
| Группа4                  |            411 |             0 |       105625 |        15.3 | object      |
| Тип                      |              5 |             0 |            0 |         0   | object      |
| Номенклатура             |          73256 |             0 |            0 |         0   | object      |
| ТипТовара                |              2 |             0 |        74690 |        10.8 | object      |
| Отменено                 |              2 |             0 |            0 |         0   | object      |
| ПричинаОтмены            |             31 |             0 |       624836 |        90.4 | object      |
| Количество               |             71 |         20307 |            0 |         0   | int64       |
| Цена                     |          16856 |             0 |            0 |         0   | object      |
| СуммаСтроки              |          17527 |             0 |            0 |         0   | object      |
| ЦенаЗакупки              |          24782 |             0 |        76913 |        11.1 | object      |
| МесяцДатыЗаказа          |              2 |             0 |            0 |         0   | int64       |
| ГодДатыЗаказа            |              1 |             0 |            0 |         0   | object      |
| ПВЗ_код                  |              4 |             0 |       228886 |        33.1 | object      |
| Статус                   |              5 |             0 |            0 |         0   | object      |
| Гео                      |              3 |             0 |            0 |         0   | object      |
| Маржа                    |          43917 |             0 |        76913 |        11.1 | object      |
| СуммаУслуг               |            151 |             0 |            0 |         0   | object      |
| СуммаДоставки            |            151 |             0 |            0 |         0   | object      |
| НомерСтроки              |            147 |             0 |            0 |         0   | int64       |
| КоличествоПроданоКлиенту |             69 |        137763 |            0 |         0   | int64       |
| ДатаЗаказаНаСайте        |             81 |             0 |            4 |         0   | object      |
| Телефон_new              |         114448 |             0 |            0 |         0   | object      |
| ЭлектроннаяПочта_new     |           6176 |             0 |        13117 |         1.9 | object      |
| Клиент                   |           5168 |             0 |          374 |         0.1 | object      |
| ID_SKU                   |          85380 |             0 |            0 |         0   | object      |
| ГородМагазина            |             64 |             0 |            0 |         0   | object      |
| МагазинЗаказа            |             89 |             0 |       686556 |        99.3 | object      |

In [305]:
df.shape

(691539, 38)

In [306]:
#удаление столбца ЭлектроннаяПочта_new.
df = df.drop(columns=['ЭлектроннаяПочта_new'])

In [307]:
df.shape

(691539, 37)

In [308]:
#удаление строк с незаполненными телефонами.
df = df.loc[df['Телефон_new'] != 0]
df = df.dropna(subset=['Телефон_new'])

In [309]:
df.shape

(691539, 37)

In [ ]:
#удаляем ненужные для анализа столбцы
df = df.drop(columns=['Дата', 'ДатаДоставки', 'СуммаДокумента', 'ЦенаЗакупки', 'ГодДатыЗаказа', 'ПВЗ_код', 'СуммаУслуг', 'СуммаДоставки', 'НомерСтроки',
                      'КоличествоПроданоКлиенту', 'ДатаЗаказаНаСайте', 'Клиент', 'ID_SKU', 'ГородМагазина', 'МагазинЗаказа', 'СуммаЗаказаНаСайте', 'Гео', 'ПричинаОтмены'])

In [311]:
df.head()

,НомерЗаказаНаСайте,НовыйСтатус,МетодДоставки,ФормаОплаты,Регион,Группа2,Группа3,Группа4,Тип,Номенклатура,ТипТовара,Отменено,Количество,Цена,СуммаСтроки,МесяцДатыЗаказа,Статус,Маржа,Телефон_new
0,3998972_TR,Частичный возврат,Курьерская,Наличная,Москва,КРУПНОГАБАРИТНЫЙ ТОВАР,КОЛЯСКИ,АКСЕССУАРЫ ДЛЯ КОЛЯСОК,КГТ,"LEADER KIDS, МУФТА на ручку коляски, (беж),",КГТ,Нет,1,680,680,3,Возврат,508,55574854-48574951555577
1,3999117_TR,Доставлен,Магазины,Безналичная,Челябинск,"ТЕКСТИЛЬ, ТРИКОТАЖ",ОДЕЖДА ДЛЯ НОВОРОЖДЕННЫХ (0-2 лет),боди,ОДЕЖДА,"GAMEX, БОДИ кор. рук. Roza, (бел/сер), р. 86, ...",МГТ,Нет,1,379,379,3,Доставлен,"169,2",55575453-56535648535679
2,3999122_TR,Доставлен,Магазины,Безналичная,Нижневартовск,ИГРУШКИ,ИГРУШКИ ДЛЯ ДЕВОЧЕК,имитационные игрушки для девочек,ИГРУШКИ,"ИГРУША, ХОЛОДИЛЬНИК (на бат), (29,5*19*45,5 см)",МГТ,Нет,1,3 325,3 325,3,Доставлен,2 176,55574950-57515657535772
3,3999363_TR,К отгрузке,Курьерская,Наличная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ОДЕЖДА ДЛЯ НОВОРОЖДЕННЫХ (0-2 лет),ползунки,ОДЕЖДА,"MAMATTI, ПОЛЗУНКИ Elephant, р. 68, Польша",МГТ,Нет,1,330,330,3,Доставлен,"163,04",55574851-55545249535475
4,3999411_TR,Доставлен,Магазины,Безналичная,Ижевск,ИГРУШКИ,ИГРУШКИ ДЛЯ РАЗВИТИЯ МАЛЫШЕЙ,игрушки для ванной,ИГРУШКИ,"S+S TOYS, ИГРУШКА ПВХ в наборе, (2 шт)",МГТ,Нет,1,199,199,3,Доставлен,120,55574854-56495552515179

In [312]:
df.shape

(691539, 19)

In [313]:
#вычисляем количество уникальных значений, количество нулей, количество пропусков, процент пропусков и тип данных
def columnValues(df):
    row = [df.nunique(), (df == 0).sum(axis=0), df.isna().sum(), round(df.isna().sum() / len(df) * 100, 1), df.dtypes]
    return row

data_3 = []
for column in df:
    data_3.append([column] + columnValues(df[column]))

print(tabulate(data_3, headers=['Column', 'Count Unique', 'Count Zeros', 'Count NaNs','% of NaNs', 'data type'], tablefmt='orgtbl'))

| Column             |   Count Unique |   Count Zeros |   Count NaNs |   % of NaNs | data type   |
|--------------------+----------------+---------------+--------------+-------------+-------------|
| НомерЗаказаНаСайте |         178418 |             0 |            4 |         0   | object      |
| НовыйСтатус        |             14 |             0 |            0 |         0   | object      |
| МетодДоставки      |              7 |             0 |            0 |         0   | object      |
| ФормаОплаты        |              2 |             0 |            0 |         0   | object      |
| Регион             |            508 |             0 |         5142 |         0.7 | object      |
| Группа2            |             13 |             0 |        74686 |        10.8 | object      |
| Группа3            |             93 |             0 |        74686 |        10.8 | object      |
| Группа4            |            411 |             0 |       105625 |        15.3 | object      |
| Тип                |              5 |             0 |            0 |         0   | object      |
| Номенклатура       |          73256 |             0 |            0 |         0   | object      |
| ТипТовара          |              2 |             0 |        74690 |        10.8 | object      |
| Отменено           |              2 |             0 |            0 |         0   | object      |
| Количество         |             71 |         20307 |            0 |         0   | int64       |
| Цена               |          16856 |             0 |            0 |         0   | object      |
| СуммаСтроки        |          17527 |             0 |            0 |         0   | object      |
| МесяцДатыЗаказа    |              2 |             0 |            0 |         0   | int64       |
| Статус             |              5 |             0 |            0 |         0   | object      |
| Маржа              |          43917 |             0 |        76913 |        11.1 | object      |
| Телефон_new        |         114448 |             0 |            0 |         0   | object      |

In [ ]:
#убираем отмененные заказы
df = df.loc[df['Отменено'] != 'Да']

In [315]:
df.shape

(623964, 19)

In [316]:
df.Статус.unique()

array(['Возврат', 'Доставлен', 'В процессе', 'Отменен', 'Не определен'],
      dtype=object)

In [317]:
df = df.loc[~df['Статус'].isin(['Не определен'])]

In [ ]:
#Заменяем названия городов Центрального ф.о
df['Регион'] = df['Регион'].replace([
    'Москва', 'Белгород', 'Владимир', 'Воронеж', 'Иваново', 'Калуга', 'Кострома', 'Курск', 
    'Липецк', 'Люберцы', 'Мытищи', 'Подольск', 'Рязань', 'Сергиев Посад', 'Серпухов', 
    'Смоленск', 'Тамбов', 'Тверь', 'Тула', 'Ярославль', 'Брянск', 'Орёл', 'Елец', 'Моршанск', 'Лиски',
    'Подольск (Московская область район)', 'Красногорск (Красногорский район)', 
    'Красково (Люберецкий район)', 'Клин (Клинский район)', 
    'Королев (Московская область район)', 'Железнодорожный (Московская область район)',
    'Балашиха (Балашихинский район)', 'Электросталь (Московская область район)',
    'Люберцы (Люберецкий район)', 'Химки (Московская область район)',
    'Жуковский (Московская область район)', 'Сергиев Посад (Сергиево-Посадский район)',
    'Дмитров (Дмитровский район)', 'Одинцово (Одинцовский район)',
    'Ногинск (Ногинский район)', 'Орехово-Зуево (Московская область район)',
    'Видное (Ленинский район)', 'Котельники (Люберецкий район)',
    'Мытищи (Мытищинский район)', 'Реутов (Московская область район)',
    'Долгопрудный (Московская область район)', 'Лобня (Московская область район)',
    'Троицк (ГП Москва)', 'Малаховка (Люберецкий район)', 'Дубна (Московская область район)',
    'Можайск (Можайский район)', 'Путилково (Красногорский район)',
    'Дзержинский (Московская область район)', 'Жостово (Мытищинский район)',
    'Истра (Красногорский район)', 'Коломна (Московская область район)',
    'Калининец (Наро-Фоминский район)', 'Щелково (Московская область район)',
    'Раменское (Раменский район)', 'Обухово (Ногинский район)',
    'Михайловка (Раменский район)', 'Электроизолятор (Раменский район)',
    'Жуково (Раменский район)', 'Суханово (Ленинский район)',
    'Константиново (Раменский район)', 'Марушкино (Наро-Фоминский район)',
    'Чиверево (Мытищинский район)','Десногорск','Ковров','Алексин', 'Зеленоград',
    'Сокол', 'Обнинск', 'Борисоглебск', 'Нововоронеж', 'Переславль-Залесский',
    'Вичуга', 'Гаврилов-Ям', 'Рыбинск', 'Кольчугино', 'Редкино (Тверская область)',
    'Мичуринск', 'Россошь', 'Судогда', 'Семилуки', 'Торжок', 'Приволжск', 'Александров',
    'Юрьевец', 'Железногорск', 'Шебекино', 'Вязьма', 'Балабаново', 'Новомичуринск',
    'Павловск (Воронежская обл.)', 'Буй', 'Сухиничи', 'Муром'
], 'Центральный ф.о.')

In [319]:
#добираем оставшиеся города Московского региона
df['Регион'] = df['Регион'].apply(
    lambda x: 'Центральный ф.о.' if isinstance(x, str) and ('москов' in x.lower() or 'район' in x.lower()) 
    else x
)

In [ ]:
#заменяем названия городов Северо-Кавказского ф.о.
df['Регион'] = df['Регион'].replace([
    'Каспийск', 'Зеленокумск', 'Железноводск', 'Ессентуки', 
    'Изобильный', 'Георгиевск', 'Светлоград', 'Буйнакск', 
    'Минеральные Воды'
], 'Северо-Кавказский ф.о.')

In [ ]:
#заменяем названия городов Северо-Западного ф.о.
df['Регион'] = df['Регион'].replace([
    'Великий Новгород', 'Вологда', 'Воркута', 'Всеволожск', 
    'Выборг', 'Гатчина', 'Кингисепп', 'Кириши', 'Колпино', 
    'Мурманск', 'Петрозаводск', 'Псков', 'Пушкин', 
    'Санкт-Петербург', 'Тихвин', 'Череповец', 'Архангельск', 
    'Полярные Зори', 'Сыктывкар', 'Ухта', 'Апатиты',
    'Калининград', 'Бокситогорск', 'Североморск', 'Заполярный', 
    'Сестрорецк', 'Сосновый Бор', 'Петергоф', 'Усинск', 
    'Кировск (Мурманская область)', 'Остров', 'Костомукша', 
    'Мурмаши (Мурманская область)', 'Кандалакша', 'Сортавала', 
    'Великие Луки', 'Красное Село', 'Сертолово', 'Печора', 
    'Оленегорск', 'Гусев', 'Северодвинск', 'Кола'
    'Кировск (Ленинградская область)', 'Осиновая роща',
    'Тосно', 'Печенга (Мурманская область)', 'Мирный (Архангельская область)', 'Кола', 
    'Кировск (Ленинградская область)'
], 'Северо-Западный ф.о.')

In [ ]:
#заменяем названия городов Приволжского ф.о.
df['Регион'] = df['Регион'].replace([
    'Ижевск', 'Казань', 'Набережные Челны', 'Нижний Новгород', 'Новокуйбышевск', 'Пенза', 
    'Пермь', 'Самара', 'Саратов', 'Тольятти', 'Ульяновск', 'Уфа', 'Чебоксары', 'Оренбург',
    'Чайковский', 'Орск', 'Киров', 'Стерлитамак', 'Йошкар-Ола', 'Старый Оскол','Балаково',
    'Медногорск', 'Дзержинск', 'Саранск', 'Бузулук', 'Димитровград', 'Можга', 'Энгельс',
    'Березники', 'Жигулёвск', 'Ишимбай', 'Арзамас', 'Лысьва', 'Кстово', 'Кунгур',
    'Павлово (Нижегородская область)', 'Мелеуз', 'Вольск', 'Сызрань', 'Шумерля',
    'Балахна', 'Зеленодольск', 'Воткинск', 'Саров', 'Глазов', 'Соликамск', 'Волжск',
    'Кирово-Чепецк', 'Цивильск', 'Полазна (Пермский край)', 'Нефтекамск', 'Ворсма',
    'Слободской', 'Чусовой', 'Шиханы', 'Кизел'
], 'Приволжский ф.о.')

In [ ]:
#заменяем названия городов Сибирского ф.о.
df['Регион'] = df['Регион'].replace([
    'Барнаул', 'Новосибирск', 'Омск', 'Томск', 'Красноярск', 'Иркутск', 'Кемерово',
    'Горно-Алтайск', 'Улан-Удэ', 'Кызыл', 'Абакан',
    'Новокузнецк', 'Братск', 'Ангарск', 'Норильск', 'Анжеро-Судженск', 'Прокопьевск',
    'Ленинск-Кузнецкий', 'Междуреченск', 'Северск', 'Ачинск', 'Канск', 'Зеленогорск',
    'Бийск', 'Рубцовск', 'Новоалтайск', 'Бердск', 'Искитим', 'Киселевск', 'Юрга',
    'Северобайкальск', 'Усолье-Сибирское', 'Черемхово', 'Минусинск', 'Кызыл',
    'Чита', 'Новоуральск', 'Ангарск', 'Братск', 'Абакан',
    'Усолье-Сибирское', 'Братск', 'Ангарск', 'Норильск', 'Ачинск', 'Канск',
    'Минусинск', 'Горно-Алтайск', 'Кызыл', 'Улан-Удэ', 'Мыски', 'Лесосибирск',
    'Усть-Кут', 'Сосновоборск', 'Усть-Илимск', 'Нижнеудинск', 'Асино',
    'Железногорск-Илимский', 'Гусиноозерск', 'Топки', 'Белово'
], 'Сибирский ф.о.')

In [ ]:
#заменяем названия городов Южного ф.о.
df['Регион'] = df['Регион'].replace([
    'Волгоград', 'Краснодар', 'Новочеркасск', 'Пятигорск', 'Ростов-на-Дону', 'Сочи', 
    'Ставрополь', 'Волжский', 'Таганрог', 'Адлер', 'Камышин', 'Астрахань',
    'Благовещенск', 'Грозный', 'Махачкала', 'Нальчик', 'Черкесск', 'Владикавказ',
    'Майкоп', 'Элиста', 'Симферополь', 'Севастополь','Новороссийск', 'Армавир',
    'Туапсе', 'Анапа', 'Шахты', 'Крымск', 'Тихорецк', 'Красный Сулин', 'Приморско-Ахтарск',
    'Темрюк', 'Каменск-Шахтинский', 'Ейск', 'Абинск', 'Урюпинск', 'Азов', 'Миллерово', 'Лабинск',
    'Геленджик', 'Горячий Ключ', 'Жирновск', 'Батайск', 'Каневская (Краснодарский край)',
    'Белая Калитва', 'Сальск', 'Гулькевичи', 'Новопокровская (Краснодарский край)', 'Волгодонск',
    'Новокубанск', 'Северская (Краснодарский край)', 'Апшеронск', 'Славянск-на-Кубани', 'Изобильный',
    'Семикаракорск', 'Белореченск', 'Зерноград', 'Майский', 'Тимашёвск', 'Котельниково', 'Кисловодск'
], 'Южный ф.о.')

In [ ]:
#заменяем названия городов Уральского ф.о.
df['Регион'] = df['Регион'].replace([
    'Екатеринбург', 'Нижневартовск', 'Нижний Тагил', 'Ноябрьск', 'Сургут', 'Тюмень', 
    'Челябинск', 'Ханты-Мансийск', 'Магнитогорск', 'Златоуст', 'Миасс', 'Курган',
    'Салават', 'Нижнекамск', 'Стерлитамак', 'Тобольск', 'Каменск-Уральский', 'Первоуральск',
    'Нижняя Тура', 'Сатка', 'Лесной', 'Алапаевск', 'Заречный (Свердловская область)', 'Лангепас',
    'Качканар', 'Нефтеюганск', 'Ревда', 'Березовский', 'Радужный (ХМАО)', 'Лянтор',
    'Касли', 'Белоярский', 'Реж', 'Среднеуральск', 'Надым', 'Троицк (Челябинская область)',
    'Чебаркуль'
], 'Уральский ф.о.')

In [ ]:
#заменяем названия городов Дальневосточного ф.о.
df['Регион'] = df['Регион'].replace([
    'Владивосток', 'Хабаровск', 'Якутск', 'Благовещенск', 'Петропавловск-Камчатский',
    'Южно-Сахалинск', 'Магадан', 'Анадырь', 'Уссурийск', 'Комсомольск-на-Амуре',
    'Находка', 'Артем', 'Нерюнгри', 'Мирный', 'Краснокаменск', 'Белогорск', 'Большой Камень',
    'Елизово'
], 'Дальневосточный ф.о.')

In [327]:
#удаляем строки с незаполненнным регионом
df = df.dropna(subset=['Регион'])

In [ ]:
#посмотрим уникальные значения получившихся Регионов
df.Регион.unique()

array(['Центральный ф.о.', 'Уральский ф.о.', 'Приволжский ф.о.',
       'Южный ф.о.', 'Сибирский ф.о.', 'Северо-Западный ф.о.',
       'Дальневосточный ф.о.', 'Северо-Кавказский ф.о.'], dtype=object)

In [329]:
df.shape

(618849, 19)

In [ ]:
#переименуем столбцы для удобства
df = df.rename(columns={'Группа2': 'Группа1', 'Группа3': 'Группа2', 'Группа4': 'Группа3'})

In [ ]:
#посмотрим уникальные значения Группы2
df.Группа2.unique()

array(['КОЛЯСКИ', 'ОДЕЖДА ДЛЯ НОВОРОЖДЕННЫХ (0-2 лет)',
       'ИГРУШКИ ДЛЯ ДЕВОЧЕК', 'ИГРУШКИ ДЛЯ РАЗВИТИЯ МАЛЫШЕЙ',
       'КОНСТРУКТОРЫ', 'ДЕТСКАЯ ОДЕЖДА (2-6 лет)', 'КАНЦТОВАРЫ',
       'КАТАЛКИ/КАЧАЛКИ', 'ПОСТЕЛЬНОЕ БЕЛЬЕ', 'ДЕТСКОЕ БЕЛЬЁ',
       'ДЕТСКИЕ СТУЛЬЯ ДЛЯ КОРМЛЕНИЯ', 'ДЕТСКАЯ МЕБЕЛЬ, МАТРАСЫ',
       'ДЕТСКИЕ КОЛГОТКИ И НОСКИ', 'ОБУВЬ ДЕТСКАЯ',
       'КОРЗИНЫ, ЯЩИКИ ДЛЯ ИГРУШЕК', 'ДЕТСКАЯ ОДЕЖДА (7-16 лет)',
       'ГОЛОВНЫЕ УБОРЫ, ВАРЕЖКИ, ПЕРЧАТКИ', 'ВЕРХНЯЯ ДЕТСКАЯ ОДЕЖДА',
       'СОПУТСТВУЮЩИЕ ТОВАРЫ ДЛЯ ОБУВИ', 'АКСЕССУАРЫ ДЛЯ ДЕВОЧЕК',
       'ИГРУШКИ ДЛЯ МАЛЬЧИКОВ', 'СПОРТИВНЫЕ КОМПЛЕКСЫ И ПЕСОЧНИЦЫ',
       'АВТОКРЕСЛА', 'ВЕЛОСИПЕДЫ/САМОКАТЫ', 'ПОДГУЗНИКИ',
       'ИЗДЕЛИЯ ИЗ ПЛАСТМАССЫ', 'БУТЫЛОЧКИ', 'СРЕДСТВА БЫТОВОЙ ХИМИИ',
       'ХОЗЯЙСТВЕННЫЕ ТОВАРЫ', 'ОДЕЖДА, ОБУВЬ', 'КОЛЯСКИ ДЛЯ КУКОЛ',
       'МАНЕЖИ/ШЕЗЛОНГИ', 'ПОЛИГРАФИЧЕСКАЯ ПРОДУКЦИЯ', 'ПОСУДА',
       'МЯГКИЕ ИГРУШКИ', 'ПРЕДМЕТЫ ПО УХОДУ ЗА НОВОРОЖДЕННЫМИ',
       'ЭЛЕКТРОПРИБОРЫ', 'НАСТОЛЬНЫЕ ИГРЫ', 'САНКИ/СНЕГОКАТЫ',
       'АКСЕССУАРЫ', 'ХОДУНКИ/ПРЫГУНКИ', 'ЭЛЕКТРОМОБИЛИ/МАШИНЫ ПЕДАЛЬНЫЕ',
       'МУЗЫКАЛЬНЫЕ ИНСТРУМЕНТЫ', 'ФИГУРЫ, ПЕРСОНАЖИ', 'ТВОРЧЕСТВО',
       'АКСЕССУАРЫ ДЛЯ ВОЛОС', 'ФОТОАЛЬБОМЫ/ФОТОРАМКИ',
       'АКСЕССУАРЫ МАКИЯЖ, МАНИКЮР', 'СОСКИ/ПУСТЫШКИ', 'ШАПКИ, ШАРФЫ',
       'АКТИВНЫЙ ОТДЫХ', 'КОПИЛКИ, БРЕЛОКИ, МАГНИТИКИ',
       'ДЕТСКАЯ КОСМЕТИКА', 'ВСЁ ДЛЯ ПРАЗДНИКА', 'ПЮРЕ',
       'СРЕДСТВА ГИГИЕНЫ', 'ТОВАРЫ ДЛЯ МАМ', 'КАШИ', 'ЗАМЕНИТЕЛИ МОЛОКА',
       'ПЕЛЕНКИ ОДНОРАЗОВЫЕ', 'КОНДИТЕРСКИЕ ИЗДЕЛИЯ',
       'КОСМЕТИКА/ГИГИЕНА ДЛЯ МАМ', 'НАПИТКИ', 'СУМКИ ДЛЯ МАМ',
       'ЧАСЫ/ОЧКИ', 'МЕДИАПРОДУКЦИЯ', 'КИСЛОМОЛОЧНЫЕ ПРОДУКТЫ', nan,
       'ТРУСИКИ НЕПРОМОКАЕМЫЕ', 'БАКАЛЕЯ', 'МОЛОКООТСОСЫ',
       'ЛАМПЫ/СВЕТИЛЬНИКИ', 'ТОВАРЫ ДЛЯ КОШЕК', 'ГАЛАНТЕРЕЯ',
       'ПРОДУКТЫ ПИТАНИЯ ДЛЯ МАМ', 'СУВЕНИРНАЯ ПРОДУКЦИЯ',
       'ВИТАМИНЫ/БАДЫ', 'ТОВАРЫ ДЛЯ СОБАК',
       'ТЕХНИКА ДЛЯ КРАСОТЫ И ЗДОРОВЬЯ', 'СУМКИ', 'ТОВАРЫ ДЛЯ ГРЫЗУНОВ',
       'ТОВАРЫ ДЛЯ РЫБ', 'ЭЛЕМЕНТЫ ПИТАНИЯ', 'ОБУВЬ ЖЕНСКАЯ',
       'ТОВАРЫ ДЛЯ ПТИЦ', 'БЫТОВАЯ ХИМИЯ ДЛЯ ЖИВОТНЫХ',
       'ТОВАРЫ ДЛЯ ХОРЬКОВ', 'ТОВАРЫ ДЛЯ ЧЕРЕПАХ И РЕПТИЛИЙ',
       'СПОРТ.ИНВЕНТАРЬ', 'БИЖУТЕРИЯ', 'ДЕКОР', 'ЗЕРКАЛА',
       'СИСТЕМЫ ХРАНЕНИЯ'], dtype=object)

In [ ]:
#посмотрим уникальные значения Группы3
df.Группа3.unique()

array(['АКСЕССУАРЫ ДЛЯ КОЛЯСОК', 'боди',
       'имитационные игрушки для девочек', 'ползунки',
       'игрушки для ванной', 'конструкторы - тип Лего', 'леггинсы',
       'предметы для рисования', 'футболки', 'рубашки', 'каталки КИТАЙ',
       'комплекты для купания', 'трусы',
       'стулья для кормления пластик КИТАЙ', 'наборы мебели (стол+стул)',
       'платья', 'джемпера', 'брюки', 'колготки', 'КОЛЯСКИ КИТАЙ',
       'повседневная обувь', 'кровати', 'ящики РОССИЯ',
       'комплекты в кровать', 'спальники', 'демисезонная обувь',
       'комплекты, наборы', 'распашонки', 'комбинезоны', 'рукавички',
       'варежки, перчатки', 'КОЛЯСКИ ЕВРОПА', 'комплекты', 'дождевики',
       'песочники', 'заколки для волос', 'транспорт для малышей',
       'модели инерционные и фрикционные', 'сандально-туфельная группа',
       'качели', 'корзины для игрушек', 'юбки', 'качалки меховые',
       'куклы/пупсы', 'транспорт радиоуправляемый',
       '15-36 кг (автокресла, бустеры)', 'носки', 'головные уборы',
       'головные уборы для новорожденных', 'шорты', 'самокаты', 'куртки',
       'подгузники прочие', 'матрасы в кровать', 'горшки', 'зонты',
       'бриджи', 'бутылочки, наборы бутылочек', 'горки', 'хоз.товары',
       'пеленки', 'коляски для кукол МЕЛОГО', 'полукомбинезоны',
       'наборы игровые для мальчиков', '0-18 кг (автокресла)',
       'манежи РОССИЯ', 'пинетки', 'доски/матрасы пеленальные',
       'коляски для кукол ИГРУША', 'мебель пластик',
       'держатели для балдахина', 'велосипеды', 'КОЛЯСКИ ПОЛЬША',
       'пластилин', 'халаты', 'книги для малышей',
       'разное (баки, ведра, тазы)',
       'стулья для кормления пластик ЕВРОПА', 'поильники, чашки',
       'конверты', 'комплекты ПБ', 'ванны', 'домашние комплекты',
       'порошки', 'отбеливатели', 'МЯГКИЕ ИГРУШКИ', 'ветровки', 'дома',
       'погремушки', 'игрушки из дерева',
       'наборы по уходу за новорожденными', 'коляски для кукол ВАКАРТ',
       '0-13 кг (люльки-переноски)', 'мольберты',
       'прочие игрушки для развития', 'столовые приборы', 'тарелки',
       'одеяла', 'коляски для кукол 1TOY', 'письменные принадлежности',
       'бумажно-беловая продукция', 'видеорадионяни',
       '9-36 кг (автокресла)', 'пазлы', 'ящики прочие',
       'спортивные товары, спорткомплексы и аксессуары',
       'аксессуары для купания', 'крестильные наборы', 'щипчики',
       'горки и сидения для купания', 'пластиковые машины', 'санки',
       'стулья для кормления деревянные', 'слюнявчики/нагрудники',
       'шарфы', 'иммитационные игрушки для мальчиков', 'наборы игровые',
       'наборы оружия', 'вожжи', 'мячи-прыгуны ПОЛЬША', 'комоды',
       'подушки', 'аспираторы', 'аксессуары для автокресел',
       'ранцы, рюкзаки, пеналы', 'электромобили', 'велобеги', 'прыгунки',
       'набор музыкальных инструментов', 'жакеты', 'животные',
       'каталки прочие', 'прочее творчество', 'комплекты (майка+трусы)',
       'ножницы', 'майки', 'жилеты', 'наборы для девочек', 'фотоальбомы',
       'комбинезоны, полукомбинезоны', 'безопасность',
       'музыкальные мобили для кроваток', 'аксессуары для кукол',
       'другие канцелярские принадлежности', 'лыжи', 'КОЛЯСКИ ЛИТВА',
       'накладки на унитаз', 'музыкальные инструменты',
       'исследования, опыты', 'бюстгалтера', 'железные дороги',
       'контейнеры/термосы', 'стельки', 'поделки', 'ходунки КИТАЙ',
       'плащи', 'растяжки', 'мембранная обувь', 'соски',
       'аксессуары к стульям для кормления', 'подарочные издания',
       'резиновая обувь', 'сортеры', 'подставки под ванну',
       'переноски для детей', 'медицинские принадлежности',
       'подставки/ступени', 'транспорт прочий', 'пустышки',
       'аксессуары для сосок и пустышек', 'роботы, трансформеры',
       'средства для мытья посуды',
       'многофункциональные развивающие центры',
       'коляски для кукол ГУСИО', 'прочие настольные игры', 'пальто',
       'комплекты в коляску', 'мягкая мебель', 'текстильная обувь',
       'гольфы', 'лопаты', 'коньки, ролики и аксессуары', 'манежи ЕВРОПА',
       'пирамидки', 'комбинированные комплекты', 'кальсоны',
       'манежи КИТАЙ', 'снегокаты', 'прорезыватели',
       'магнитные конструкторы', 'мифические существа',
       'средства для стерилизации', 'стерилизаторы', 'щетки, расчески',
       'накидки', 'мыло для стирки', 'песочницы', 'подвижные игры',
       'развивающие коврики', 'брелоки', 'пляжная обувь',
       'аксессуары для мебели', 'прочие конструкторы', 'зимняя обувь',
       'ленты', 'треки, парковки', 'скейтборды', 'мыло',
       'блочные конструкторы', 'Новый год - украшения',
       'обучающие книги для детей', 'ершики', 'оружие', 'термометры',
       'спортивные наборы', 'кондиционеры для белья', 'зубная паста',
       'наборы посуды', 'подгузники', 'пюре фруктовые', 'пюре овощные',
       'диски ватные', 'салфетки',
       'образовательная литература для родителей', 'для праздника другое',
       'свечи', 'пакеты/сумки', 'трусики-подгузники',
       'раскраски, наклейки', 'косметика для мам', 'каши натуральные',
       'шампуни', 'пенки', 'ЗАМЕНИТЕЛИ МОЛОКА', 'пюре мясные',
       'пюре ассорти', 'прокладки/тампоны', 'лосьоны/молочко',
       'бумага туалетная', 'многофункциональные книги',
       'одноразовая посуда', 'пена', 'ПЕЛЕНКИ ОДНОРАЗОВЫЕ', 'присыпки',
       'крема', 'палочки ватные', 'художественная литература',
       'щетки зубные', 'КОНДИТЕРСКИЕ ИЗДЕЛИЯ', 'средства для купания',
       'пюре рыбные', 'шары надувные', 'гигиена для кормления', 'масла',
       'соки', 'энциклопедии', 'мозаики', 'гели', 'освежители воздуха',
       'губки, мочалки', 'каши с наполнителем', 'защита от насекомых',
       'одежда для мам', 'настольно-печатные игры', 'СУМКИ ДЛЯ МАМ',
       'ЧАСЫ/ОЧКИ', 'аудиодиски', 'мыльные пузыри',
       'солнцезащитные средства', 'спреи', 'напитки разные',
       'декоративная косметика', 'йогурт', 'наборы косметические',
       'платки носовые', 'аксессуары для бутылочек', 'карнавал',
       'каталки ручные', 'электронные игры', 'рукоделие', 'купальники',
       'матрешки, неваляшки, пирамидки', 'ТРУСИКИ НЕПРОМОКАЕМЫЕ',
       'галстуки, ремни, помочи', 'кубики', 'лото/домино', 'открытки',
       'деревянные конструкторы', 'фоторамки', 'бакалея прочие',
       'чепчики', 'жидкие каши', 'мякиши', 'МОЛОКООТСОСЫ',
       'тюбинги/подушки', 'светильники', 'шезлонги', 'клеющие модели',
       'клеенки', 'домашняя обувь', 'термобелье', 'полотенца', 'супы',
       'игрушки для песка/снега', 'журналы', 'спортивные игры', 'люди',
       'кукольный театр', 'вода', 'радиоуправляемые игрушки для малышей',
       'металлические и пластмассовые шурупные конструкторы',
       'ПРОДУКТЫ ПИТАНИЯ ДЛЯ МАМ', 'спринцовки', 'магнитики',
       'матрасы в санки', 'прочие товары для обуви', 'головоломки',
       'подогреватели', 'ДЕТСКАЯ ОДЕЖДА (7-16 лет)', 'качалки пластик',
       'модели масштабные', 'весы', 'Новый год - сувенирная продукция',
       'Новый год - ёлки', 'гимнастические костюмы',
       'принадлежности для плавания', 'аксессуары', 'КОЛЯСКИ ДЛЯ КУКОЛ',
       'столы пеленальные', 'носовые платки', 'соль', 'витамины/бады',
       'предметы', 'стаканы', 'бижутерия', 'молочные коктейли',
       'ДЕТСКАЯ ОДЕЖДА (2-6 лет)', 'коврики для ванной', 'водное оружие',
       'шкафы', 'СУМКИ', 'фляжки', 'ДЕТСКОЕ БЕЛЬЁ', 'ЭЛЕМЕНТЫ ПИТАНИЯ',
       'машинки для девочек', 'сумки для девочек', 'молоко',
       'ОДЕЖДА ДЛЯ НОВОРОЖДЕННЫХ (0-2 лет)', 'утилизация подгузников',
       'домики, палатки игровые, замки', 'ледянки', 'манежи-кровати',
       'чешки/балетки', 'автохимия', 'терки', 'ночные сорочки',
       'игровые приставки', 'комбайны',
       'аксессуары к велосипедам/самокатам',
       'ГОЛОВНЫЕ УБОРЫ, ВАРЕЖКИ, ПЕРЧАТКИ', 'прочие изделия', 'накидка',
       'каталки ЕВРОПА', 'КАТАЛКИ/КАЧАЛКИ', 'детские площадки', 'грелки',
       'конструкторы для мальчиков', 'лампы', 'ФИГУРЫ, ПЕРСОНАЖИ',
       'ходунки ЕВРОПА', 'хлебные изделия', 'люльки-переноски',
       'машины педальные', 'коляски для кукол ПОЛЕСЬЕ', 'шкатулки',
       'пиджаки', 'шнурки', 'ЗЕРКАЛА', 'снеки', 'видеодиски'],
      dtype=object)

In [333]:
#вычисляем количество уникальных значений, количество нулей, количество пропусков, процент пропусков и тип данных
def columnValues(df):
    row = [df.nunique(), (df == 0).sum(axis=0), df.isna().sum(), round(df.isna().sum() / len(df) * 100, 1), df.dtypes]
    return row

data_3 = []
for column in df:
    data_3.append([column] + columnValues(df[column]))

print(tabulate(data_3, headers=['Column', 'Count Unique', 'Count Zeros', 'Count NaNs','% of NaNs', 'data type'], tablefmt='orgtbl'))

| Column             |   Count Unique |   Count Zeros |   Count NaNs |   % of NaNs | data type   |
|--------------------+----------------+---------------+--------------+-------------+-------------|
| НомерЗаказаНаСайте |         160783 |             0 |            0 |         0   | object      |
| НовыйСтатус        |             13 |             0 |            0 |         0   | object      |
| МетодДоставки      |              6 |             0 |            0 |         0   | object      |
| ФормаОплаты        |              2 |             0 |            0 |         0   | object      |
| Регион             |              8 |             0 |            0 |         0   | object      |
| Группа1            |             13 |             0 |        73679 |        11.9 | object      |
| Группа2            |             92 |             0 |        73679 |        11.9 | object      |
| Группа3            |            409 |             0 |       100831 |        16.3 | object      |
| Тип                |              5 |             0 |            0 |         0   | object      |
| Номенклатура       |          70265 |             0 |            0 |         0   | object      |
| ТипТовара          |              2 |             0 |        73679 |        11.9 | object      |
| Отменено           |              1 |             0 |            0 |         0   | object      |
| Количество         |             67 |             0 |            0 |         0   | int64       |
| Цена               |          15592 |             0 |            0 |         0   | object      |
| СуммаСтроки        |          16424 |             0 |            0 |         0   | object      |
| МесяцДатыЗаказа    |              2 |             0 |            0 |         0   | int64       |
| Статус             |              4 |             0 |            0 |         0   | object      |
| Маржа              |          41865 |             0 |        75075 |        12.1 | object      |
| Телефон_new        |         106412 |             0 |            0 |         0   | object      |

In [ ]:
#посмотрим когда Группа3 и Группа2 не содержит информацию
result = df[
    df['Группа2'].isna() & 
    df['Группа3'].isna()
]
print(tabulate(result.head()))

-----  ----------  ----------  ----------  -----------  ----------------  ---  ---  ---  ----  --------  ---  ---  -  ---  ---  -  ---------  ---  -----------------------
31873  3998962_TR  Доставлен   Магазины    Безналичная  Центральный ф.о.  nan  nan  nan  ИНОЕ  Доставка  nan  Нет  1   49   49  3  Доставлен  nan  55575057-53555757515473
31879  3998998_TR  Доставлен   Магазины    Безналичная  Центральный ф.о.  nan  nan  nan  ИНОЕ  Доставка  nan  Нет  1   49   49  3  Доставлен  nan  55575057-53574856545476
31890  3999056_TR  К отгрузке  Pick point  Безналичная  Центральный ф.о.  nan  nan  nan  ИНОЕ  Доставка  nan  Нет  1  180  180  3  Доставлен  nan  55574857-54545052535273
31957  3999641_TR  Доставлен   Магазины    Безналичная  Приволжский ф.о.  nan  nan  nan  ИНОЕ  Доставка  nan  Нет  1   99   99  3  Доставлен  nan  55575655-54485754524877
32028  3999665_TR  Доставлен   Магазины    Безналичная  Приволжский ф.о.  nan  nan  nan  ИНОЕ  Доставка  nan  Нет  1   99   99  3  Доставлен  nan  55574857-54485351525577
-----  ----------  ----------  ----------  -----------  ----------------  ---  ---  ---  ----  --------  ---  ---  -  ---  ---  -  ---------  ---  -----------------------

In [335]:
df = df.loc[df['Тип'] != 'ИНОЕ']

In [ ]:
#посмотрим когда Группа3 не содержит информацию
result = df[df['Группа3'].isna()
]
print(tabulate(result.head()))

----  ----------  ----------  ----------  -----------  ----------------  -------  --------------  ---  -------  ---------------------------------------------------------  ---  ---  -  -----  -----  -  ---------  -----  -----------------------
 287  4063341_TR  Доставлен   Магазины    Безналичная  Центральный ф.о.  ИГРУШКИ  МЯГКИЕ ИГРУШКИ  nan  ИГРУШКИ  LEADER KIDS, ИГРУШКА мягконабив.Немецкая овчарка, (26 см)  МГТ  Нет  1  1 099  1 099  3  Доставлен  712    55574948-52525049525370
 884  4087389_TR  К отгрузке  Курьерская  Наличная     Центральный ф.о.  ИГРУШКИ  МЯГКИЕ ИГРУШКИ  nan  ИГРУШКИ  LEADER KIDS, ИГРУШКА мягконабив. Енот, (20 см)             МГТ  Нет  1  649    649    3  Доставлен  451    55575053-48515749545776
1438  4093310_TR  Доставлен   Магазины    Безналичная  Центральный ф.о.  ИГРУШКИ  МЯГКИЕ ИГРУШКИ  nan  ИГРУШКИ  S+S TOYS, ИГРУШКА интеракт.Собачка, (на бат)               МГТ  Нет  1  288    288    3  Доставлен  33,94  0
2169  4099879_TR  К отгрузке  Курьерская  Наличная     Центральный ф.о.  ИГРУШКИ  МЯГКИЕ ИГРУШКИ  nan  ИГРУШКИ  LEADER KIDS, ИГРУШКА мягконабив.Медведь в шапке, (25 см)   МГТ  Нет  1  255    255    3  Доставлен  23     55574857-57555049485277
2176  4099879_TR  К отгрузке  Курьерская  Наличная     Центральный ф.о.  ИГРУШКИ  МЯГКИЕ ИГРУШКИ  nan  ИГРУШКИ  LEADER KIDS, ИГРУШКА мягконабив.Медведь в шапке, (25 см)   МГТ  Нет  1  255    255    3  Доставлен  23     55574857-57555049485277
----  ----------  ----------  ----------  -----------  ----------------  -------  --------------  ---  -------  ---------------------------------------------------------  ---  ---  -  -----  -----  -  ---------  -----  -----------------------

In [ ]:
#заполним пустые значения Группы3 значениями Группы2
df = df.copy()
df['Группа3'] = df['Группа3'].fillna(df['Группа2'])

In [338]:
df.shape

(537698, 19)

In [339]:
#вычисляем количество уникальных значений, количество нулей, количество пропусков, процент пропусков и тип данных
def columnValues(df):
    row = [df.nunique(), (df == 0).sum(axis=0), df.isna().sum(), round(df.isna().sum() / len(df) * 100, 1), df.dtypes]
    return row

data_3 = []
for column in df:
    data_3.append([column] + columnValues(df[column]))

print(tabulate(data_3, headers=['Column', 'Count Unique', 'Count Zeros', 'Count NaNs','% of NaNs', 'data type'], tablefmt='orgtbl'))

| Column             |   Count Unique |   Count Zeros |   Count NaNs |   % of NaNs | data type   |
|--------------------+----------------+---------------+--------------+-------------+-------------|
| НомерЗаказаНаСайте |         152034 |             0 |            0 |         0   | object      |
| НовыйСтатус        |             13 |             0 |            0 |         0   | object      |
| МетодДоставки      |              6 |             0 |            0 |         0   | object      |
| ФормаОплаты        |              2 |             0 |            0 |         0   | object      |
| Регион             |              8 |             0 |            0 |         0   | object      |
| Группа1            |             10 |             0 |            0 |         0   | object      |
| Группа2            |             71 |             0 |            0 |         0   | object      |
| Группа3            |            380 |             0 |            0 |         0   | object      |
| Тип                |              4 |             0 |            0 |         0   | object      |
| Номенклатура       |          68127 |             0 |            0 |         0   | object      |
| ТипТовара          |              2 |             0 |            0 |         0   | object      |
| Отменено           |              1 |             0 |            0 |         0   | object      |
| Количество         |             66 |             0 |            0 |         0   | int64       |
| Цена               |          15493 |             0 |            0 |         0   | object      |
| СуммаСтроки        |          16315 |             0 |            0 |         0   | object      |
| МесяцДатыЗаказа    |              2 |             0 |            0 |         0   | int64       |
| Статус             |              4 |             0 |            0 |         0   | object      |
| Маржа              |          41125 |             0 |         1249 |         0.2 | object      |
| Телефон_new        |         102452 |             0 |            0 |         0   | object      |