Import

In [91]:
import pandas as pd
import numpy as np
import seaborn as sns
from tabulate import tabulate
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [92]:
df_original = pd.read_csv(
    "/Users/danzh/OneDrive/Рабочий стол/vs/project/project-clusters/sales.csv",
    sep=None, 
    engine='python'
)

Data preparation

In [93]:
df = df_original.copy()

In [94]:
df.head()

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,Группа3,Группа4,Тип,Номенклатура,ТипТовара,Отменено,ПричинаОтмены,Количество,Цена,СуммаСтроки,ЦенаЗакупки,МесяцДатыЗаказа,ГодДатыЗаказа,ПВЗ_код,Статус,Гео,Маржа,СуммаУслуг,СуммаДоставки,НомерСтроки,КоличествоПроданоКлиенту,ДатаЗаказаНаСайте,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа
0,01.03.2017 11:41,07.03.2017 0:00,3998972_TR,Частичный возврат,12 098,12 247,Курьерская,Наличная,Москва,КРУПНОГАБАРИТНЫЙ ТОВАР,КОЛЯСКИ,АКСЕССУАРЫ ДЛЯ КОЛЯСОК,КГТ,"LEADER KIDS, МУФТА на ручку коляски, (беж),",КГТ,Нет,NaN,1,680,680,172,3,2 017,NaN,Возврат,Москва,508,0,0,8,1,28.02.2017 0:00,55574854-48574951555577,106117_ju18@yandex.ru,Юлия,ID9010020114553,0,NaN
1,01.03.2017 12:22,15.03.2017 0:00,3999117_TR,Доставлен,4 819,3 759,Магазины,Безналичная,Челябинск,"ТЕКСТИЛЬ, ТРИКОТАЖ",ОДЕЖДА ДЛЯ НОВОРОЖДЕННЫХ (0-2 лет),боди,ОДЕЖДА,"GAMEX, БОДИ кор. рук. Roza, (бел/сер), р. 86, ...",МГТ,Нет,NaN,1,379,379,"209,8",3,2 017,23111,Доставлен,Регионы,"169,2",0,0,3,1,01.03.2017 0:00,55575453-56535648535679,107117_ku16@list.ru,Гость,IDL00028974351,0,NaN
2,01.03.2017 12:31,17.03.2017 0:00,3999122_TR,Доставлен,3 325,3 325,Магазины,Безналичная,Нижневартовск,ИГРУШКИ,ИГРУШКИ ДЛЯ ДЕВОЧЕК,имитационные игрушки для девочек,ИГРУШКИ,"ИГРУША, ХОЛОДИЛЬНИК (на бат), (29,5*19*45,5 см)",МГТ,Нет,NaN,1,3 325,3 325,1 149,3,2 017,23111,Доставлен,Регионы,2 176,0,0,1,1,01.03.2017 0:00,55574950-57515657535772,109117_mu17@mail.ru,Гость,IDL00038573351,0,NaN
3,01.03.2017 3:06,02.03.2017 0:00,3999363_TR,К отгрузке,4 998,4 998,Курьерская,Наличная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ОДЕЖДА ДЛЯ НОВОРОЖДЕННЫХ (0-2 лет),ползунки,ОДЕЖДА,"MAMATTI, ПОЛЗУНКИ Elephant, р. 68, Польша",МГТ,Нет,NaN,1,330,330,"166,96",3,2 017,NaN,Доставлен,Москва,"163,04",0,0,4,0,01.03.2017 0:00,55574851-55545249535475,115117_su13@mail.ru,Гость,IDL00034303856,0,NaN
4,01.03.2017 11:38,14.03.2017 0:00,3999411_TR,Доставлен,528,528,Магазины,Безналичная,Ижевск,ИГРУШКИ,ИГРУШКИ ДЛЯ РАЗВИТИЯ МАЛЫШЕЙ,игрушки для ванной,ИГРУШКИ,"S+S TOYS, ИГРУШКА ПВХ в наборе, (2 шт)",МГТ,Нет,NaN,1,199,199,79,3,2 017,23111,Доставлен,Регионы,120,0,0,3,1,01.03.2017 0:00,55574854-56495552515179,guest_103117_gu28@workmail.ru,Гость,IDL00035791553,0,NaN

In [95]:
#вычисляем количество уникальных значений, количество нулей, количество пропусков, процент пропусков и тип данных
def columnValues(df):
    row = [df.nunique(), (df == 0).sum(axis=0), df.isna().sum(), round(df.isna().sum() / len(df) * 100, 1), df.dtypes]
    return row

data = []
for column in df:
    data.append([column] + columnValues(df[column]))

print(tabulate(data, headers=['Column', 'Count Unique', 'Count Zeros', 'Count NaNs','% of NaNs', 'data type'], tablefmt='orgtbl'))

| Column                   |   Count Unique |   Count Zeros |   Count NaNs |   % of NaNs | data type   |
|--------------------------+----------------+---------------+--------------+-------------+-------------|
| Дата                     |          28887 |             0 |            0 |         0   | object      |
| ДатаДоставки             |            107 |             0 |          626 |         0.1 | object      |
| НомерЗаказаНаСайте       |         178418 |             0 |            4 |         0   | object      |
| НовыйСтатус              |             14 |             0 |            0 |         0   | object      |
| СуммаЗаказаНаСайте       |          14316 |             0 |            0 |         0   | object      |
| СуммаДокумента           |          14747 |             0 |            0 |         0   | object      |
| МетодДоставки            |              7 |             0 |            0 |         0   | object      |
| ФормаОплаты              |              2 |             0 |            0 |         0   | object      |
| Регион                   |            508 |             0 |         5142 |         0.7 | object      |
| Группа2                  |             13 |             0 |        74686 |        10.8 | object      |
| Группа3                  |             93 |             0 |        74686 |        10.8 | object      |
| Группа4                  |            411 |             0 |       105625 |        15.3 | object      |
| Тип                      |              5 |             0 |            0 |         0   | object      |
| Номенклатура             |          73256 |             0 |            0 |         0   | object      |
| ТипТовара                |              2 |             0 |        74690 |        10.8 | object      |
| Отменено                 |              2 |             0 |            0 |         0   | object      |
| ПричинаОтмены            |             31 |             0 |       624836 |        90.4 | object      |
| Количество               |             71 |         20307 |            0 |         0   | int64       |
| Цена                     |          16856 |             0 |            0 |         0   | object      |
| СуммаСтроки              |          17527 |             0 |            0 |         0   | object      |
| ЦенаЗакупки              |          24782 |             0 |        76913 |        11.1 | object      |
| МесяцДатыЗаказа          |              2 |             0 |            0 |         0   | int64       |
| ГодДатыЗаказа            |              1 |             0 |            0 |         0   | object      |
| ПВЗ_код                  |              4 |             0 |       228886 |        33.1 | object      |
| Статус                   |              5 |             0 |            0 |         0   | object      |
| Гео                      |              3 |             0 |            0 |         0   | object      |
| Маржа                    |          43917 |             0 |        76913 |        11.1 | object      |
| СуммаУслуг               |            151 |             0 |            0 |         0   | object      |
| СуммаДоставки            |            151 |             0 |            0 |         0   | object      |
| НомерСтроки              |            147 |             0 |            0 |         0   | int64       |
| КоличествоПроданоКлиенту |             69 |        137763 |            0 |         0   | int64       |
| ДатаЗаказаНаСайте        |             81 |             0 |            4 |         0   | object      |
| Телефон_new              |         114448 |             0 |            0 |         0   | object      |
| ЭлектроннаяПочта_new     |           6176 |             0 |        13117 |         1.9 | object      |
| Клиент                   |           5168 |             0 |          374 |         0.1 | object      |
| ID_SKU                   |          85380 |             0 |            0 |         0   | object      |
| ГородМагазина            |             64 |             0 |            0 |         0   | object      |
| МагазинЗаказа            |             89 |             0 |       686556 |        99.3 | object      |

In [96]:
df.shape

(691539, 38)

In [97]:
#удаление столбца Телефон_new.
df = df.drop(columns=['Телефон_new'])

In [98]:
df.shape

(691539, 37)

In [99]:
#удаление строк с незаполненными почтами.
df = df.loc[df['ЭлектроннаяПочта_new'] != 0]
df = df.dropna(subset=['ЭлектроннаяПочта_new'])

In [100]:
df.shape

(678422, 37)

In [101]:
df = df.drop(columns=['Дата', 'ДатаДоставки', 'СуммаДокумента', 'ЦенаЗакупки', 'ГодДатыЗаказа', 'ПВЗ_код', 'СуммаУслуг', 'СуммаДоставки', 'НомерСтроки',
                      'КоличествоПроданоКлиенту', 'ДатаЗаказаНаСайте', 'Клиент', 'ID_SKU', 'ГородМагазина', 'МагазинЗаказа', 'СуммаЗаказаНаСайте', 'Гео'])

In [102]:
df.head()

,НомерЗаказаНаСайте,НовыйСтатус,МетодДоставки,ФормаОплаты,Регион,Группа2,Группа3,Группа4,Тип,Номенклатура,ТипТовара,Отменено,ПричинаОтмены,Количество,Цена,СуммаСтроки,МесяцДатыЗаказа,Статус,Маржа,ЭлектроннаяПочта_new
0,3998972_TR,Частичный возврат,Курьерская,Наличная,Москва,КРУПНОГАБАРИТНЫЙ ТОВАР,КОЛЯСКИ,АКСЕССУАРЫ ДЛЯ КОЛЯСОК,КГТ,"LEADER KIDS, МУФТА на ручку коляски, (беж),",КГТ,Нет,NaN,1,680,680,3,Возврат,508,106117_ju18@yandex.ru
1,3999117_TR,Доставлен,Магазины,Безналичная,Челябинск,"ТЕКСТИЛЬ, ТРИКОТАЖ",ОДЕЖДА ДЛЯ НОВОРОЖДЕННЫХ (0-2 лет),боди,ОДЕЖДА,"GAMEX, БОДИ кор. рук. Roza, (бел/сер), р. 86, ...",МГТ,Нет,NaN,1,379,379,3,Доставлен,"169,2",107117_ku16@list.ru
2,3999122_TR,Доставлен,Магазины,Безналичная,Нижневартовск,ИГРУШКИ,ИГРУШКИ ДЛЯ ДЕВОЧЕК,имитационные игрушки для девочек,ИГРУШКИ,"ИГРУША, ХОЛОДИЛЬНИК (на бат), (29,5*19*45,5 см)",МГТ,Нет,NaN,1,3 325,3 325,3,Доставлен,2 176,109117_mu17@mail.ru
3,3999363_TR,К отгрузке,Курьерская,Наличная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ОДЕЖДА ДЛЯ НОВОРОЖДЕННЫХ (0-2 лет),ползунки,ОДЕЖДА,"MAMATTI, ПОЛЗУНКИ Elephant, р. 68, Польша",МГТ,Нет,NaN,1,330,330,3,Доставлен,"163,04",115117_su13@mail.ru
4,3999411_TR,Доставлен,Магазины,Безналичная,Ижевск,ИГРУШКИ,ИГРУШКИ ДЛЯ РАЗВИТИЯ МАЛЫШЕЙ,игрушки для ванной,ИГРУШКИ,"S+S TOYS, ИГРУШКА ПВХ в наборе, (2 шт)",МГТ,Нет,NaN,1,199,199,3,Доставлен,120,guest_103117_gu28@workmail.ru

In [103]:
df.shape

(678422, 20)

In [104]:
def columnValues(df):
    row = [df.nunique(), (df == 0).sum(axis=0), df.isna().sum(), round(df.isna().sum() / len(df) * 100, 1), df.dtypes]
    return row

data_3 = []
for column in df:
    data_3.append([column] + columnValues(df[column]))

print(tabulate(data_3, headers=['Column', 'Count Unique', 'Count Zeros', 'Count NaNs','% of NaNs', 'data type'], tablefmt='orgtbl'))

| Column               |   Count Unique |   Count Zeros |   Count NaNs |   % of NaNs | data type   |
|----------------------+----------------+---------------+--------------+-------------+-------------|
| НомерЗаказаНаСайте   |         170803 |             0 |            0 |         0   | object      |
| НовыйСтатус          |             14 |             0 |            0 |         0   | object      |
| МетодДоставки        |              7 |             0 |            0 |         0   | object      |
| ФормаОплаты          |              2 |             0 |            0 |         0   | object      |
| Регион               |            500 |             0 |          160 |         0   | object      |
| Группа2              |             13 |             0 |        72872 |        10.7 | object      |
| Группа3              |             93 |             0 |        72872 |        10.7 | object      |
| Группа4              |            411 |             0 |       103399 |        15.2 | object      |
| Тип                  |              5 |             0 |            0 |         0   | object      |
| Номенклатура         |          72473 |             0 |            0 |         0   | object      |
| ТипТовара            |              2 |             0 |        72872 |        10.7 | object      |
| Отменено             |              2 |             0 |            0 |         0   | object      |
| ПричинаОтмены        |             31 |             0 |       613119 |        90.4 | object      |
| Количество           |             69 |         20027 |            0 |         0   | int64       |
| Цена                 |          16593 |             0 |            0 |         0   | object      |
| СуммаСтроки          |          17243 |             0 |            0 |         0   | object      |
| МесяцДатыЗаказа      |              2 |             0 |            0 |         0   | int64       |
| Статус               |              5 |             0 |            0 |         0   | object      |
| Маржа                |          43029 |             0 |        75036 |        11.1 | object      |
| ЭлектроннаяПочта_new |           6176 |             0 |            0 |         0   | object      |

In [105]:
df.ПричинаОтмены.unique()

array([nan, 'Возврат товара', '5.3 Другое',
       '4.04 Не пришел товар от поставщика',
       '2.1 Не устроила дата доставки',
       '1.4 Ошибка выбора, будет новый заказ', '1.0 Форсмажор',
       'Авто корректировка склада',
       '2.5 Отказ из за переноса даты доставки',
       '4.01 Нет на остатках или нет в обработке ЗПЗ',
       '5.1 Уже купил товар в другом месте',
       '2.3 Не устроила стоимость доставки', '1.5 Письмо об отмене',
       '4.02 Нет основных позиций заказа',
       '2.2 Не устроило время (часы) доставки',
       '3.4 Не устроило отсутствие бонусов или скидок',
       '1.3 Не верные контактные данные или нет связи с клиентом',
       '2.4 Нет доставки в данный город (регион)',
       'Авто корректировка ЗПЗ', '1.2 Повторный заказ (дубль заказа)',
       '1.1 Тест, контрольная закупка', '4.05 Ошибка реализации',
       '3.1 Не устроили условия оплаты или резервирования (предоплата, срок резерва)',
       '3.6 Ошибка списания или начисления баллов', '4.06 Пересорт',
       '3.5 Будет новый заказ после получения бонусной карты',
       '4.03 Нет нужной ассортиментной позиции (цвет, размер, тип)',
       '3.3 Несоотв. стоимости товара или цена не устроила',
       '3.2 Несоотв. характеристик товара (свойства, картинка, цвет)',
       '4.07 Ошибка интеграции DPD',
       '5.2 Истек срок хранения товара при самовывоз',
       '4.10 Не найдено в местах хранения'], dtype=object)

In [106]:
df = df.loc[~df['ПричинаОтмены'].isin(['1.4 Ошибка выбора, будет новый заказ', '1.1 Тест, контрольная закупка', '4.05 Ошибка реализации',
                  '3.6 Ошибка списания или начисления баллов', '3.5 Будет новый заказ после получения бонусной карты',
                  '4.07 Ошибка интеграции DPD','1.2 Повторный заказ (дубль заказа)'])]

In [107]:
df.shape

(670161, 20)

In [108]:
df.Статус.unique()

array(['Возврат', 'Доставлен', 'В процессе', 'Отменен', 'Не определен'],
      dtype=object)

In [109]:
df = df.loc[~df['Статус'].isin(['Не определен'])]

In [110]:
df.Регион.unique()

array(['Москва', 'Челябинск', 'Нижневартовск', 'Ижевск',
       'Подольск (Московская область район)',
       'Красногорск (Красногорский район)', 'Красково (Люберецкий район)',
       'Клин (Клинский район)', 'Саратов', 'Волжский', 'Таганрог',
       'Смоленск', 'Пермь', 'Королев (Московская область район)',
       'Железнодорожный (Московская область район)', 'Самара',
       'Новосибирск', 'Сочи', 'Барнаул', 'Балашиха (Балашихинский район)',
       'Тюмень', 'Электросталь (Московская область район)', 'Краснодар',
       'Иваново', 'Тамбов', 'Астрахань', 'Люберцы (Люберецкий район)',
       'Химки (Московская область район)',
       'Жуковский (Московская область район)', 'Йошкар-Ола',
       'Новомосковск', 'Воронеж', 'Калуга', 'Брянск', 'Санкт-Петербург',
       'Пенза', 'Тула', 'Улан-Удэ', 'Гатчина', 'Ростов-на-Дону',
       'Сергиев Посад (Сергиево-Посадский район)', 'Благовещенск',
       'Липецк', 'Архангельск', 'Рязань', 'Екатеринбург',
       'Дмитров (Дмитровский район)', 'Нижний Новгород',
       'Одинцово (Одинцовский район)', 'Белгород', 'Омск',
       'Ногинск (Ногинский район)',
       'Орехово-Зуево (Московская область район)',
       'Видное (Ленинский район)', 'Котельники (Люберецкий район)',
       'Мытищи (Мытищинский район)', 'Орск',
       'Реутов (Московская область район)', 'Уфа',
       'Долгопрудный (Московская область район)', 'Орёл', 'Сургут',
       'Камышин', 'Чита', 'Томск', 'Курск', 'Стерлитамак', 'Ульяновск',
       'Адлер', 'Лобня (Московская область район)', 'Тольятти', 'Киров',
       'Троицк (ГП Москва)', 'Ярославль', 'Малаховка (Люберецкий район)',
       'Волгоград', 'Старый Оскол', 'Оренбург', 'Тверь',
       'Набережные Челны', 'Дубна (Московская область район)',
       'Можайск (Можайский район)', 'Путилково (Красногорский район)',
       'Чайковский', 'Дзержинский (Московская область район)',
       'Жостово (Мытищинский район)', 'Ставрополь', 'Казань', 'Владимир',
       'Истра (Красногорский район)',
       'Коломна (Московская область район)', 'Кемерово',
       'Калининец (Наро-Фоминский район)', 'Красноярск',
       'Домодедово (Домодедовский район)', 'Десногорск',
       'Наро-Фоминск (Наро-Фоминский район)', 'Иркутск',
       'Митино (Волоколамский район)', 'Голицыно (Одинцовский район)',
       'Марусино (Люберецкий район)', 'Симферополь', 'Тобольск',
       'Щелково (Щелковский район)',
       'Павловский Посад (Павлово-Посадский район)', 'Южно-Сахалинск',
       'Краснокаменск', 'Мотяково (Люберецкий район)',
       'Бронницы (Московская область район)', 'Магнитогорск',
       'Севастополь', 'Ковров', 'Балаково', 'Новороссийск',
       'Чулково (Раменский район)', 'Новочеркасск',
       'Звенигород (Московская область район)', 'Колпино', 'Алексин',
       'Солнечногорск (Солнечногорский район)',
       'Воскресенск (Воскресенский район)', 'Медногорск', 'Полярные Зори',
       'Дедовск (Истринский район)', 'Чебоксары', 'Норильск', 'Махачкала',
       'Электрогорск (Павлово-Посадский район)', 'Мыски', 'Зеленоград',
       'Столбовая (Чеховский район)', 'Раменское (Раменский район)',
       'Ангелово (Красногорский район)', 'Хабаровск',
       'Щербинка (Московская область район)',
       'Егорьевск (Егорьевский район)', 'Томилино (Люберецкий район)',
       'Свердловский (Щелковский район)', 'Элиста',
       'Юбилейный (Московская область район)', 'Каменск-Уральский',
       'Магадан', 'Первоуральск', 'Ступино (Ступинский район)',
       'Нахабино (Красногорский район)', 'Развилка (Ленинский район)',
       'Армавир', 'Дзержинск', 'Электроугли (Ногинский район)',
       'Ивантеевка (Московская область район)',
       'Коммунарка (Ленинский район)', 'Московский (Ленинский район)',
       'Овражки (Люберецкий район)', 'Миасс',
       'Балобаново (Ногинский район)', 'Бийск', 'Туапсе', 'Ухта',
       'Пятигорск', 'Внуково (Волоколамский район)',
       'Некрасовский (Дмитровский район)', 'Майкоп', 'Анапа', 'Мурманск',
       'Лесной Городок (Одинцовский район)', 'Петропавловск-Камчатский',
       'Озеры (Озерский район)', 'Серпухов (Московская область район)',
       'Сабурово (Красногорский район)', 'Мосрентген (Ленинский район)',
       'Белая (Ногинский район)', 'Чехов (Чеховский район)',
       'Лыткарино (Московская область район)', 'Псков', 'Шахты',
       'Саранск', 'Белогорск', 'Долгое Ледово (Щелковский район)',
       'Братск', 'Волоколамск (Волоколамский район)', 'Ханты-Мансийск',
       'Воркута', 'Менделеево (Солнечногорский район)', 'Владивосток',
       'Климовск (Московская область район)', 'Сатка',
       'Володарского (Ленинский район)', 'Лесной', 'Черкесск', 'Апатиты',
       'Сокол', 'Ногинск-4 (Ногинский район)',
       'Островцы (Раменский район)', 'Бузулук',
       'Пироговский (Мытищинский район)', 'Боброво (Ленинский район)',
       'Заря (Балашихинский район)', 'Череповец', 'Нерюнгри',
       'Калининград', 'Мытищи 16 (Мытищинский район)',
       'Вялки (Раменский район)', 'Талдом (Талдомский район)', 'Крымск',
       'Петрозаводск', 'Румянцево (Истринский район)', 'Тихорецк',
       'Дрожжино (Ленинский район)', 'Апрелевка (Наро-Фоминский район)',
       'Красный Сулин', 'Новоивановское (Одинцовский район)',
       'Кашира (Каширский район)', 'Приморско-Ахтарск', 'Кингисепп',
       'Толстопальцево ОПХ (Наро-Фоминский район)',
       'Шатура (Шатурский район)', 'Димитровград',
       'Черноголовка (Ногинский район)', 'Булатниково (Ленинский район)',
       'Истра (Истринский район)', 'Бокситогорск',
       'Сосенки (Ленинский район)', 'Павловское (Истринский район)',
       'Темрюк', 'Североморск', nan, 'Можга', 'Златоуст', 'Сыктывкар',
       'Каспийск', 'Заполярный', 'Лунево (Солнечногорский район)',
       'Сестрорецк', 'Нижний Тагил', 'Челюскинский (Пушкинский район)',
       'Обнинск', 'Энгельс', 'Виноградово (Воскресенский район)',
       'Зверосовхоз (Пушкинский район)', 'Пушкин', 'Новокузнецк',
       'Нальчик', 'Бутово (Ленинский район)', 'Марьино (Ленинский район)',
       'Борисоглебск', 'Глебово (Истринский район)',
       'Кудиново (Ногинский район)', 'Сосновый Бор', 'Нововоронеж',
       'Анискино (Щелковский район)', 'Загорянский (Щелковский район)',
       'Зеленокумск', 'Нижнекамск', 'Березники',
       'Красноармейск (Московская область район)', 'Каменск-Шахтинский',
       'Переславль-Залесский', 'Жигулёвск', 'Верея (Раменский район)',
       'Алапаевск', 'Вологда', 'Брехово (Солнечногорский район)',
       'Петергоф', 'Заречный (Свердловская область)', 'Ейск',
       'Железноводск', 'Куровское (Орехово-Зуевский район)', 'Усинск',
       'Курилово (Подольский район)',
       'Краснознаменск (Московская область район)', 'Абинск',
       'Селятино (Наро-Фоминский район)',
       'Архангельское (Красногорский район)', 'Ишимбай', 'Кострома',
       'Урюпинск', 'Вичуга', 'Лосино-Петровский (Щелковский район)',
       'Краснозаводск (Сергиево-Посадский район)', 'Гаврилов-Ям', 'Азов',
       'Луховицы (Луховицкий район)', 'Арзамас', 'Рыбинск',
       'Кировск (Мурманская область)', 'Остров', 'Прокопьевск', 'Лысьва',
       'Кстово', 'Костомукша', 'Миллерово',
       'Рошаль (Московская область район)', 'Молоково (Ленинский район)',
       'Лесосибирск', 'Грозный', 'Новокуйбышевск', 'Лабинск',
       'Пушкино (Пушкинский район)', 'Мисайлово (Ленинский район)',
       'Геленджик', 'Усть-Кут', 'Ступино (Домодедовский район)',
       'Мурмаши (Мурманская область)', 'Уссурийск', 'Лангепас',
       'Кандалакша', 'Владикавказ', 'Немчиновка (Одинцовский район)',
       'Горячий Ключ', 'Кольчугино', 'Тельмана (Раменский район)',
       'Качканар', 'Жирновск', 'Рождествено (Истринский район)',
       'Батайск', 'Старая Купавна (Ногинский район)',
       'Ликино-Дулево (Орехово-Зуевский район)', 'Сосновоборск',
       'Переделкино (Ленинский район)', 'Монино (Щелковский район)',
       'Люберцы-2 (Люберецкий район)',
       'Белоозерский (Воскресенский район)', 'Быково (Раменский район)',
       'Каневская (Краснодарский край)', 'Руза (Рузский район)',
       'Фрязино (Московская область район)',
       'Правдинский (Пушкинский район)', 'Удельная (Раменский район)',
       'Сортавала', 'Гаврилково-2 (Красногорский район)',
       'Одинцово-1 (Одинцовский район)', 'Редкино (Тверская область)',
       'Белая Калитва', 'Ватутинки (Ленинский район)', 'Кунгур',
       'Заречье (Одинцовский район)', 'Нефтеюганск', 'Ревда',
       'Баковка (Одинцовский район)', 'Сальск', 'Великий Новгород',
       'Мичуринск', 'Великие Луки', 'Усть-Илимск',
       'Павлово (Нижегородская область)', 'Мелеуз', 'Россошь',
       'Гольево (Красногорский район)', 'Красное Село', 'Сертолово',
       'Березовский', 'Гулькевичи', 'Новопокровская (Краснодарский край)',
       'Вольск', 'Якутск', 'Снегири (Истринский район)', 'Сухиничи',
       'Тосно', 'Слободской', 'Чусовой', 'Ромашково (Одинцовский район)',
       'Майский', 'Радужный (ХМАО)', 'Судогда', 'Выборг', 'Семилуки',
       'Всеволожск', 'Рубцовск', 'Волгодонск', 'Салават', 'Новокубанск',
       'Северская (Краснодарский край)', 'Сызрань',
       'Печенга (Мурманская область)', 'Мирный (Архангельская область)',
       'Апшеронск', 'Шумерля', 'Кубинка (Одинцовский район)',
       'Нижнеудинск', 'Зеленый (Ногинский район)', 'Печора', 'Балахна',
       'Зеленодольск', 'Касли', 'Оленегорск',
       'Софрино (Пушкинский район)', 'Воткинск', 'Славянск-на-Кубани',
       'Асино', 'Гусев', 'Саров', 'ВНИИССОК (Одинцовский район)',
       'Северодвинск', 'Ессентуки', 'Глазов', 'Торжок',
       'Опалиха (Красногорский район)', 'Внуково (Ленинский район)',
       'Воскресенское (Ленинский район)', 'Соликамск',
       'Чехов-8 (Чеховский район)', 'Волжск',
       'Медвежьи Озера (Щелковский район)', 'Белоярский',
       'Ногинск-5 (Ногинский район)', 'Купавна (Талдомский район)',
       'Румянцево (Ленинский район)', 'Троицкое (Мытищинский район)',
       'Реж', 'Кирово-Чепецк', 'Большие Вяземы (Одинцовский район)',
       'Изобильный', 'Знамя Октября (Подольский район)', 'Тимашёвск',
       'Обухово (Ногинский район)', 'Котельниково', 'Кисловодск',
       'Демихово (Демиховское с/п) (Орехово-Зуевский район)',
       'Павловская Слобода (Истринский район)', 'Абакан', 'Минусинск',
       'Кокошкино (Наро-Фоминский район)', 'Кола',
       'Козино (Красногорский район)', 'Шиханы', 'Муром', 'Кизел',
       'Среднеуральск', 'Вешки (Мытищинский район)',
       'Черкизово (Пушкинский район)', 'Коняшино (Раменский район)',
       'Устиновка (Раменский район)', 'Воскресенское (Каширский район)',
       'Щапово (Подольский район)', 'Западный (Люберецкий район)',
       'Михнево (Домодедовский район)', 'Ерино (Подольский район)',
       'Барвиха (Одинцовский район)', 'Ногинск-9 (Ногинский район)',
       'Черная (Истринский район)', 'Приволжск', 'Бердск', 'Александров',
       'Киселевск', 'Назарьево (Одинцовский район)', 'Большой Камень',
       'Семикаракорск', 'Георгиевск', 'Щемилово (Ногинский район)',
       'Белореченск', 'Одинцово-10 (Одинцовский район)',
       'Серпухов-15 (Серпуховский район)', 'Юрьевец', 'Зерноград',
       'Светлоград', 'Покровское (Истринский район)',
       'Сапроново (Ленинский район)', 'Ленинск-Кузнецкий', 'Буйнакск',
       'Железногорск', 'Цивильск', 'Полазна (Пермский край)',
       'Железногорск-Илимский', 'Надым',
       'Усово-Тупик (Одинцовский район)', 'Дорохово (Рузский район)',
       'Тучково (Рузский район)', 'Шебекино',
       'Ильинский (Раменский район)', 'Кировск (Ленинградская область)',
       'Вязьма', 'Троицк (Челябинская область)', 'Нефтекамск', 'Ангарск',
       'Гусиноозерск', 'Яхрома (Дмитровский район)',
       'Шишкин Лес (Подольский район)', 'Топки',
       'Кратово (Раменский район)', 'Минеральные Воды', 'Белово',
       'Елизово', 'Ачинск', 'Чебаркуль', 'Балабаново', 'Новомичуринск',
       'Павловск (Воронежская обл.)', 'Чехов-3 (Чеховский район)', 'Буй',
       'Александровка (Красногорский район)', 'Осиновая роща',
       'Электроизолятор (Раменский район)', 'Жуково (Раменский район)',
       'Елец', 'Лиски', 'Новоуральск', 'Моршанск',
       'Суханово (Ленинский район)', 'Константиново (Раменский район)',
       'Марушкино (Наро-Фоминский район)', 'Чиверево (Мытищинский район)'],
      dtype=object)

In [113]:
df['Регион'] = df['Регион'].replace([
    'Москва', 'Белгород', 'Владимир', 'Воронеж', 'Иваново', 'Калуга', 'Кострома', 'Курск', 
    'Липецк', 'Люберцы', 'Мытищи', 'Подольск', 'Рязань', 'Сергиев Посад', 'Серпухов', 
    'Смоленск', 'Тамбов', 'Тверь', 'Тула', 'Ярославль',
    'Красногорск', 'Клин', 'Королев', 'Железнодорожный', 'Балашиха', 'Электросталь', 
    'Химки', 'Жуковский', 'Новомосковск', 'Одинцово', 'Ногинск', 'Орехово-Зуево', 'Видное', 
    'Котельники', 'Реутов', 'Долгопрудный', 'Лобня', 'Дмитров', 'Орёл', 'Елец', 'Моршанск',
    'Красково', 'Чиверево', 'Марушкино', 'Суханово', 'Константиново', 'Жуково', 'Электроизолятор'
], 'Центральный ф.о.')
df['Регион'] = df['Регион'].replace([
    'Великий Новгород', 'Вологда', 'Воркута', 'Всеволожск', 'Выборг', 'Гатчина', 'Кингисепп', 
    'Кириши', 'Колпино', 'Мурманск', 'Петрозаводск', 'Псков', 'Пушкин', 'Санкт-Петербург', 
    'Тихвин', 'Череповец','Архангельск'], 'Северо-Западный ф.о.')
df['Регион'] = df['Регион'].replace([
    'Ижевск', 'Казань', 'Набережные Челны', 'Нижний Новгород', 'Новокуйбышевск', 'Пенза', 
    'Пермь', 'Самара', 'Саратов', 'Тольятти', 'Ульяновск', 'Уфа', 'Чебоксары',
    'Орск', 'Киров', 'Стерлитамак', 'Йошкар-Ола', 'Октябрьский', 'Салават', 'Нефтекамск', 
    'Ишимбай', 'Заинск', 'Бугульма', 'Альметьевск', 'Лениногорск', 'Чистополь', 'Зеленодольск',
    'Дзержинск', 'Арзамас', 'Саранск'], 'Приволжский ф.о.')
df['Регион'] = df['Регион'].replace([
    'Барнаул', 'Горно-Алтайск', 'Иркутск', 'Кемерово', 'Красноярск', 'Новокузнецк', 
    'Новосибирск', 'Омск', 'Томск',
    'Кызыл', 'Абакан', 'Чита', 'Улан-Удэ', 'Бийск', 'Рубцовск', 'Новоалтайск', 
    'Прокопьевск', 'Ленинск-Кузнецкий', 'Междуреченск', 'Ангарск', 'Усолье-Сибирское', 
    'Черемхово', 'Новоуральск'], 'Сибирский ф.о.')
df['Регион'] = df['Регион'].replace([
    'Волгоград', 'Краснодар', 'Новочеркасск', 'Пятигорск', 'Ростов-на-Дону', 'Сочи', 'Ставрополь',
    'Волжский', 'Таганрог', 'Адлер', 'Камышин', 'Астрахань', 'Майкоп', 'Элиста', 
    'Симферополь', 'Севастополь', 'Махачкала', 'Нальчик', 'Черкесск', 'Владикавказ', 'Грозный'
], 'Южный ф.о.')
df['Регион'] = df['Регион'].replace([
    'Екатеринбург', 'Нижневартовск', 'Нижний Тагил', 'Ноябрьск', 'Сургут', 'Тюмень', 'Челябинск',
    'Ханты-Мансийск', 'Когалым', 'Нягань', 'Мегион', 'Лангепас', 'Пыть-Ях', 'Урай', 'Лянтор'
], 'Уральский ф.о.')
df['Регион'] = df['Регион'].replace({'Владивосток': 'Дальневосточный ф.о.'})

In [115]:
df.Регион.unique()

array(['Центральный ф.о.', 'Уральский ф.о.', 'Приволжский ф.о.',
       'Подольск (Московская область район)',
       'Красногорск (Красногорский район)', 'Красково (Люберецкий район)',
       'Клин (Клинский район)', 'Южный ф.о.',
       'Королев (Московская область район)',
       'Железнодорожный (Московская область район)', 'Сибирский ф.о.',
       'Балашиха (Балашихинский район)',
       'Электросталь (Московская область район)',
       'Люберцы (Люберецкий район)', 'Химки (Московская область район)',
       'Жуковский (Московская область район)', 'Брянск',
       'Северо-Западный ф.о.', 'Сергиев Посад (Сергиево-Посадский район)',
       'Благовещенск', 'Дмитров (Дмитровский район)',
       'Одинцово (Одинцовский район)', 'Ногинск (Ногинский район)',
       'Орехово-Зуево (Московская область район)',
       'Видное (Ленинский район)', 'Котельники (Люберецкий район)',
       'Мытищи (Мытищинский район)', 'Реутов (Московская область район)',
       'Долгопрудный (Московская область район)',
       'Лобня (Московская область район)', 'Троицк (ГП Москва)',
       'Малаховка (Люберецкий район)', 'Старый Оскол', 'Оренбург',
       'Дубна (Московская область район)', 'Можайск (Можайский район)',
       'Путилково (Красногорский район)', 'Чайковский',
       'Дзержинский (Московская область район)',
       'Жостово (Мытищинский район)', 'Истра (Красногорский район)',
       'Коломна (Московская область район)',
       'Калининец (Наро-Фоминский район)',
       'Домодедово (Домодедовский район)', 'Десногорск',
       'Наро-Фоминск (Наро-Фоминский район)',
       'Митино (Волоколамский район)', 'Голицыно (Одинцовский район)',
       'Марусино (Люберецкий район)', 'Тобольск',
       'Щелково (Щелковский район)',
       'Павловский Посад (Павлово-Посадский район)', 'Южно-Сахалинск',
       'Краснокаменск', 'Мотяково (Люберецкий район)',
       'Бронницы (Московская область район)', 'Магнитогорск', 'Ковров',
       'Балаково', 'Новороссийск', 'Чулково (Раменский район)',
       'Звенигород (Московская область район)', 'Алексин',
       'Солнечногорск (Солнечногорский район)',
       'Воскресенск (Воскресенский район)', 'Медногорск', 'Полярные Зори',
       'Дедовск (Истринский район)', 'Норильск',
       'Электрогорск (Павлово-Посадский район)', 'Мыски', 'Зеленоград',
       'Столбовая (Чеховский район)', 'Раменское (Раменский район)',
       'Ангелово (Красногорский район)', 'Хабаровск',
       'Щербинка (Московская область район)',
       'Егорьевск (Егорьевский район)', 'Томилино (Люберецкий район)',
       'Свердловский (Щелковский район)',
       'Юбилейный (Московская область район)', 'Каменск-Уральский',
       'Магадан', 'Первоуральск', 'Ступино (Ступинский район)',
       'Нахабино (Красногорский район)', 'Развилка (Ленинский район)',
       'Армавир', 'Электроугли (Ногинский район)',
       'Ивантеевка (Московская область район)',
       'Коммунарка (Ленинский район)', 'Московский (Ленинский район)',
       'Овражки (Люберецкий район)', 'Миасс',
       'Балобаново (Ногинский район)', 'Туапсе', 'Ухта',
       'Внуково (Волоколамский район)',
       'Некрасовский (Дмитровский район)', 'Анапа',
       'Лесной Городок (Одинцовский район)', 'Петропавловск-Камчатский',
       'Озеры (Озерский район)', 'Серпухов (Московская область район)',
       'Сабурово (Красногорский район)', 'Мосрентген (Ленинский район)',
       'Белая (Ногинский район)', 'Чехов (Чеховский район)',
       'Лыткарино (Московская область район)', 'Шахты', 'Белогорск',
       'Долгое Ледово (Щелковский район)', 'Братск',
       'Волоколамск (Волоколамский район)',
       'Менделеево (Солнечногорский район)', 'Дальневосточный ф.о.',
       'Климовск (Московская область район)', 'Сатка',
       'Володарского (Ленинский район)', 'Лесной', 'Апатиты', 'Сокол',
       'Ногинск-4 (Ногинский район)', 'Островцы (Раменский район)',
       'Бузулук', 'Пироговский (Мытищинский район)',
       'Боброво (Ленинский район)', 'Заря (Балашихинский район)',
       'Нерюнгри', 'Калининград', 'Мытищи 16 (Мытищинский район)',
       'Вялки (Раменский район)', 'Талдом (Талдомский район)', 'Крымск',
       'Румянцево (Истринский район)', 'Тихорецк',
       'Дрожжино (Ленинский район)', 'Апрелевка (Наро-Фоминский район)',
       'Красный Сулин', 'Новоивановское (Одинцовский район)',
       'Кашира (Каширский район)', 'Приморско-Ахтарск',
       'Толстопальцево ОПХ (Наро-Фоминский район)',
       'Шатура (Шатурский район)', 'Димитровград',
       'Черноголовка (Ногинский район)', 'Булатниково (Ленинский район)',
       'Истра (Истринский район)', 'Бокситогорск',
       'Сосенки (Ленинский район)', 'Павловское (Истринский район)',
       'Темрюк', 'Североморск', nan, 'Можга', 'Златоуст', 'Сыктывкар',
       'Каспийск', 'Заполярный', 'Лунево (Солнечногорский район)',
       'Сестрорецк', 'Челюскинский (Пушкинский район)', 'Обнинск',
       'Энгельс', 'Виноградово (Воскресенский район)',
       'Зверосовхоз (Пушкинский район)', 'Бутово (Ленинский район)',
       'Марьино (Ленинский район)', 'Борисоглебск',
       'Глебово (Истринский район)', 'Кудиново (Ногинский район)',
       'Сосновый Бор', 'Нововоронеж', 'Анискино (Щелковский район)',
       'Загорянский (Щелковский район)', 'Зеленокумск', 'Нижнекамск',
       'Березники', 'Красноармейск (Московская область район)',
       'Каменск-Шахтинский', 'Переславль-Залесский', 'Жигулёвск',
       'Верея (Раменский район)', 'Алапаевск',
       'Брехово (Солнечногорский район)', 'Петергоф',
       'Заречный (Свердловская область)', 'Ейск', 'Железноводск',
       'Куровское (Орехово-Зуевский район)', 'Усинск',
       'Курилово (Подольский район)',
       'Краснознаменск (Московская область район)', 'Абинск',
       'Селятино (Наро-Фоминский район)',
       'Архангельское (Красногорский район)', 'Урюпинск', 'Вичуга',
       'Лосино-Петровский (Щелковский район)',
       'Краснозаводск (Сергиево-Посадский район)', 'Гаврилов-Ям', 'Азов',
       'Луховицы (Луховицкий район)', 'Рыбинск',
       'Кировск (Мурманская область)', 'Остров', 'Лысьва', 'Кстово',
       'Костомукша', 'Миллерово', 'Рошаль (Московская область район)',
       'Молоково (Ленинский район)', 'Лесосибирск', 'Лабинск',
       'Пушкино (Пушкинский район)', 'Мисайлово (Ленинский район)',
       'Геленджик', 'Усть-Кут', 'Ступино (Домодедовский район)',
       'Мурмаши (Мурманская область)', 'Уссурийск', 'Кандалакша',
       'Немчиновка (Одинцовский район)', 'Горячий Ключ', 'Кольчугино',
       'Тельмана (Раменский район)', 'Качканар', 'Жирновск',
       'Рождествено (Истринский район)', 'Батайск',
       'Старая Купавна (Ногинский район)',
       'Ликино-Дулево (Орехово-Зуевский район)', 'Сосновоборск',
       'Переделкино (Ленинский район)', 'Монино (Щелковский район)',
       'Люберцы-2 (Люберецкий район)',
       'Белоозерский (Воскресенский район)', 'Быково (Раменский район)',
       'Каневская (Краснодарский край)', 'Руза (Рузский район)',
       'Фрязино (Московская область район)',
       'Правдинский (Пушкинский район)', 'Удельная (Раменский район)',
       'Сортавала', 'Гаврилково-2 (Красногорский район)',
       'Одинцово-1 (Одинцовский район)', 'Редкино (Тверская область)',
       'Белая Калитва', 'Ватутинки (Ленинский район)', 'Кунгур',
       'Заречье (Одинцовский район)', 'Нефтеюганск', 'Ревда',
       'Баковка (Одинцовский район)', 'Сальск', 'Мичуринск',
       'Великие Луки', 'Усть-Илимск', 'Павлово (Нижегородская область)',
       'Мелеуз', 'Россошь', 'Гольево (Красногорский район)',
       'Красное Село', 'Сертолово', 'Березовский', 'Гулькевичи',
       'Новопокровская (Краснодарский край)', 'Вольск', 'Якутск',
       'Снегири (Истринский район)', 'Сухиничи', 'Тосно', 'Слободской',
       'Чусовой', 'Ромашково (Одинцовский район)', 'Майский',
       'Радужный (ХМАО)', 'Судогда', 'Семилуки', 'Волгодонск',
       'Новокубанск', 'Северская (Краснодарский край)', 'Сызрань',
       'Печенга (Мурманская область)', 'Мирный (Архангельская область)',
       'Апшеронск', 'Шумерля', 'Кубинка (Одинцовский район)',
       'Нижнеудинск', 'Зеленый (Ногинский район)', 'Печора', 'Балахна',
       'Касли', 'Оленегорск', 'Софрино (Пушкинский район)', 'Воткинск',
       'Славянск-на-Кубани', 'Асино', 'Гусев', 'Саров',
       'ВНИИССОК (Одинцовский район)', 'Северодвинск', 'Ессентуки',
       'Глазов', 'Торжок', 'Опалиха (Красногорский район)',
       'Внуково (Ленинский район)', 'Воскресенское (Ленинский район)',
       'Соликамск', 'Чехов-8 (Чеховский район)', 'Волжск',
       'Медвежьи Озера (Щелковский район)', 'Белоярский',
       'Ногинск-5 (Ногинский район)', 'Купавна (Талдомский район)',
       'Румянцево (Ленинский район)', 'Троицкое (Мытищинский район)',
       'Реж', 'Кирово-Чепецк', 'Большие Вяземы (Одинцовский район)',
       'Изобильный', 'Знамя Октября (Подольский район)', 'Тимашёвск',
       'Обухово (Ногинский район)', 'Котельниково', 'Кисловодск',
       'Демихово (Демиховское с/п) (Орехово-Зуевский район)',
       'Павловская Слобода (Истринский район)', 'Минусинск',
       'Кокошкино (Наро-Фоминский район)', 'Кола',
       'Козино (Красногорский район)', 'Шиханы', 'Муром', 'Кизел',
       'Среднеуральск', 'Вешки (Мытищинский район)',
       'Черкизово (Пушкинский район)', 'Коняшино (Раменский район)',
       'Устиновка (Раменский район)', 'Воскресенское (Каширский район)',
       'Щапово (Подольский район)', 'Западный (Люберецкий район)',
       'Михнево (Домодедовский район)', 'Ерино (Подольский район)',
       'Барвиха (Одинцовский район)', 'Ногинск-9 (Ногинский район)',
       'Черная (Истринский район)', 'Приволжск', 'Бердск', 'Александров',
       'Киселевск', 'Назарьево (Одинцовский район)', 'Большой Камень',
       'Семикаракорск', 'Георгиевск', 'Щемилово (Ногинский район)',
       'Белореченск', 'Одинцово-10 (Одинцовский район)',
       'Серпухов-15 (Серпуховский район)', 'Юрьевец', 'Зерноград',
       'Светлоград', 'Покровское (Истринский район)',
       'Сапроново (Ленинский район)', 'Буйнакск', 'Железногорск',
       'Цивильск', 'Полазна (Пермский край)', 'Железногорск-Илимский',
       'Надым', 'Усово-Тупик (Одинцовский район)',
       'Дорохово (Рузский район)', 'Тучково (Рузский район)', 'Шебекино',
       'Ильинский (Раменский район)', 'Кировск (Ленинградская область)',
       'Вязьма', 'Троицк (Челябинская область)', 'Гусиноозерск',
       'Яхрома (Дмитровский район)', 'Шишкин Лес (Подольский район)',
       'Топки', 'Кратово (Раменский район)', 'Минеральные Воды', 'Белово',
       'Елизово', 'Ачинск', 'Чебаркуль', 'Балабаново', 'Новомичуринск',
       'Павловск (Воронежская обл.)', 'Чехов-3 (Чеховский район)', 'Буй',
       'Александровка (Красногорский район)', 'Осиновая роща',
       'Электроизолятор (Раменский район)', 'Жуково (Раменский район)',
       'Лиски', 'Суханово (Ленинский район)',
       'Константиново (Раменский район)',
       'Марушкино (Наро-Фоминский район)', 'Чиверево (Мытищинский район)'],
      dtype=object)